[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.27.0"
futures-util = "0.3"
futures-channel = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
